/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjni_HelloJNI */

#ifndef _Included_myjni_HelloJNI
#define _Included_myjni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
