/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNIPrimitive */

#ifndef _Included_TestJNIPrimitive
#define _Included_TestJNIPrimitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIPrimitive
 * Method:    average
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_TestJNIPrimitive_average
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     TestJNIPrimitive
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestJNIPrimitive_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TestJNIPrimitive
 * Method:    sumAverage
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_TestJNIPrimitive_sumAverage
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     TestJNIPrimitive
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestJNIPrimitive_modifyInstanceVariable
  (JNIEnv *, jobject);

/*
 * Class:     TestJNIPrimitive
 * Method:    modifyStaticVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestJNIPrimitive_modifyStaticVariable
  (JNIEnv *, jobject);

/*
 * Class:     TestJNIPrimitive
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestJNIPrimitive_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
